#!/usr/bin/env python
import sys
import requests
payload = {"CLASS":sys.argv[1], "ACTION": sys.argv[2],"ID":sys.argv[3],"DATA":sys.argv[4]}
print(requests.post("http://107.170.44.215/JamCloud/Backend/objectcommand.php",data=payload).text);
